project:
  type: website
  output-dir: docs

website:
  title: "{repicentre}"
  navbar:
    left:
      - pathway.qmd
      - explore.qmd
      - resources.qmd
      - about.qmd

format:
  html:
    theme:
      light: lightly
      dark: darkly
    highlight-style: github
    css: styles.css
    toc: true
    include-in-header:
      text: <script type="text/javascript" src="../script.js"></script>
    execute:
      echo: true
      eval: false

comments:
  hypothesis: false

