project:
  type: website

website:
  title: "Repicentre"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pathway.qmd
        text: Pathway
      - href: explore.qmd
        text: Explore
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    code-link: true
    toc: true
    include-before-body:
      text: <script type="text/javascript" src="../script.js"></script>



